sonar.projectKey=gokulmathim_streamview-platform-89100
sonar.organization=gokulmathim


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=streamview-platform-89100
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
